# Generated by Django 4.2.7 on 2023-11-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=30)),
                ('grado', models.IntegerField()),
                ('duracion', models.CharField(max_length=30)),
                ('reseñas', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=30)),
                ('tipo_documento', models.IntegerField()),
                ('numero_documento', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=30)),
                ('certificado', models.CharField(max_length=30)),
                ('rol', models.IntegerField(choices=[(1, 'admin'), (2, 'estudiante'), (3, 'docente')], default=2)),
            ],
        ),
    ]
