# Generated by Django 4.2.7 on 2023-11-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourschool', '0003_alter_usuario_certificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(max_length=30),
        ),
    ]
