# Generated by Django 4.2.7 on 2024-01-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourschool', '0004_alter_usuario_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'estudiante'), (3, 'docente')]),
        ),
    ]
