# Generated by Django 4.2.7 on 2024-01-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourschool', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='certificado',
        ),
    ]
