# Generated by Django 4.2.7 on 2024-03-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourschool', '0007_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensajes_chat', models.TextField()),
            ],
        ),
    ]
