# Generated by Django 4.2.7 on 2024-03-26 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ourschool', '0008_mensajes_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes_chat',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='ourschool.usuario'),
            preserve_default=False,
        ),
    ]
