# Generated by Django 5.0.4 on 2024-05-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourschool', '0010_remove_mensajes_chat_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='archivos/%Y/%m/%d/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
