# Generated by Django 5.0.4 on 2024-05-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourschool', '0011_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='fecha_subida',
        ),
    ]
