# Generated by Django 5.2.8 on 2025-11-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourschool', '0012_remove_archivo_fecha_subida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='asesoria',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
        migrations.DeleteModel(
            name='Mensajes_chat',
        ),
        migrations.DeleteModel(
            name='pagos',
        ),
    ]
