# Generated by Django 5.2.8 on 2025-11-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourschool', '0014_nota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
