# Generated by Django 5.2.8 on 2025-12-02 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourschool', '0015_delete_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=40)),
                ('foto', models.ImageField(upload_to='ganado/')),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourschool.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EventoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('parto', 'Parto'), ('palpacion', 'Palpación'), ('destete', 'Destete')], max_length=20)),
                ('fecha', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourschool.animal')),
            ],
        ),
    ]
