# Generated by Django 5.2.8 on 2025-12-03 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourschool', '0017_eventoanimal_descripcion_alter_animal_dueño_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoanimal',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='animal',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourschool.usuario'),
        ),
        migrations.AlterField(
            model_name='eventoanimal',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ourschool.animal'),
        ),
        migrations.AlterField(
            model_name='eventoanimal',
            name='tipo',
            field=models.CharField(choices=[('parto', 'Parto'), ('palpacion', 'Palpación'), ('destete', 'Destete'), ('nacimiento', 'Nacimiento')], max_length=20),
        ),
    ]
