# Generated by Django 5.2.8 on 2025-12-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourschool', '0018_remove_eventoanimal_descripcion_alter_animal_dueño_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoanimal',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
