# Generated by Django 5.2.8 on 2025-12-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourschool', '0020_alter_animal_foto_alter_usuario_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaleventoanimal',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='historicaleventoanimal',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalusuario',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalArchivo',
        ),
        migrations.DeleteModel(
            name='HistoricalEventoAnimal',
        ),
        migrations.DeleteModel(
            name='HistoricalUsuario',
        ),
    ]
